export const routes = {
    signIn: '/',
    signUp: '/sign-up',
    userGuide: '/user-guide',
    dashboard: '/dashboard',
    addApplication: '/application/add',
    viewApplications: '/application/view',
    addInterview: '/interview/add',
    viewInterviews: '/interview/view',
    archivedApplications: '/application/archive',
    archivedInterviews: '/interview/archive',
    demoRoot: '/demo',
    demoDashboard: '/demo/dashboard',
    demoAddApplication: '/demo/application/add',
    demoViewApplications: '/demo/application/view',
    demoAddInterview: '/demo/interview/add',
    demoViewInterviews: '/demo/interview/view',
    demoArchivedApplications: '/demo/application/archive',
    demoArchivedInterviews: '/demo/interview/archive',
} as const;
