export const endpointConfig = {
    authentication: {
        signIn: { url: '/authentication/sessions', verb: 'POST' },
        signUp: { url: '/authentication/users', verb: 'POST' },
        verify: { url: '/authentication/sessions/current', verb: 'GET', retry: true },
        refresh: { url: '/authentication/sessions/refresh', verb: 'POST' },
        logout: { url: '/authentication/sessions/current', verb: 'DELETE' },
    },
    application: {
        listApplications: {
            url: '/job-applications',
            verb: 'GET',
            fieldMap: { jobStatuses: 'query' },
            retry: true,
        },
        listWeeklyApplications: { url: '/job-applications/weekly-counts', verb: 'GET', retry: true },
        listJobStatusCounts: { url: '/job-applications/status-counts', verb: 'GET', retry: true },
        getSummary: { url: '/job-applications/summary', verb: 'GET', retry: true },
        getRelationSummary: {
            url: '/job-applications/:jobId/relation-summary',
            verb: 'GET',
            fieldMap: { jobId: 'path' },
            retry: true,
        },
        createApplication: { url: '/job-applications', verb: 'POST' },
        deleteApplication: {
            url: '/job-applications/:jobId',
            verb: 'DELETE',
            fieldMap: { jobId: 'path' },
        },
        deleteAllApplications: { url: '/job-applications', verb: 'DELETE' },
        updateNotes: {
            url: '/job-applications/:jobId/notes',
            verb: 'PATCH',
            fieldMap: { jobId: 'path' },
            retry: true,
        },
        updateStatus: {
            url: '/job-applications/:jobId/status',
            verb: 'PATCH',
            fieldMap: { jobId: 'path' },
            retry: true,
        },
    },
    interview: {
        listInterviews: {
            url: '/job-interviews',
            verb: 'GET',
            fieldMap: { timeFilters: 'query' },
            retry: true,
        },
        getSummary: { url: '/job-interviews/summary', verb: 'GET', retry: true },
        createInterview: { url: '/job-interviews', verb: 'POST' },
        deleteInterview: {
            url: '/job-interviews/:interviewId',
            verb: 'DELETE',
            fieldMap: { interviewId: 'path' },
        },
        deleteAllInterviews: { url: '/job-interviews', verb: 'DELETE' },
    },
    archivedApplication: {
        listApplications: {
            url: '/archived-job-applications',
            verb: 'GET',
            fieldMap: { jobStatuses: 'query' },
            retry: true,
        },
        archiveApplication: { url: '/archived-job-applications', verb: 'PATCH' },
        archiveAllApplications: { url: '/archived-job-applications/archive-all', verb: 'PATCH' },
        unarchiveAllApplications: { url: '/archived-job-applications/unarchive-all', verb: 'PATCH' },
        getSummary: { url: '/archived-job-applications/summary', verb: 'GET', retry: true },
        getRelationSummary: {
            url: '/archived-job-applications/:archivedJobId/relation-summary',
            verb: 'GET',
            fieldMap: { archivedJobId: 'path' },
            retry: true,
        },
        deleteApplication: {
            url: '/archived-job-applications/:archivedJobId',
            verb: 'DELETE',
            fieldMap: { archivedJobId: 'path' },
        },
        deleteAllApplications: { url: '/archived-job-applications', verb: 'DELETE' },
        unarchiveApplication: {
            url: '/archived-job-applications/:archivedJobId/restore',
            verb: 'PATCH',
            fieldMap: { archivedJobId: 'path' },
        },
    },
    archivedInterview: {
        listInterviews: {
            url: '/archived-job-interviews',
            verb: 'GET',
            fieldMap: { timeFilters: 'query' },
            retry: true,
        },
        getSummary: { url: '/archived-job-interviews/summary', verb: 'GET', retry: true },
        deleteInterview: {
            url: '/archived-job-interviews/:archivedInterviewId',
            verb: 'DELETE',
            fieldMap: { archivedInterviewId: 'path' },
        },
        deleteAllInterviews: { url: '/archived-job-interviews', verb: 'DELETE' },
    },
    offerDecision: {
        getActive: {
            url: '/offer-decisions',
            verb: 'GET',
            fieldMap: { filters: 'query' },
            retry: true,
        },
        getArchived: {
            url: '/offer-decisions/archived',
            verb: 'GET',
            fieldMap: { filters: 'query' },
            retry: true,
        },
        deleteAllActiveEvaluations: { url: '/offer-decisions', verb: 'DELETE' },
        deleteAllArchivedEvaluations: { url: '/offer-decisions/archived', verb: 'DELETE' },
        saveEvaluation: {
            url: '/offer-decisions/:jobId',
            verb: 'PUT',
            fieldMap: { jobId: 'path' },
            retry: true,
        },
        deleteEvaluation: {
            url: '/offer-decisions/:jobId',
            verb: 'DELETE',
            fieldMap: { jobId: 'path' },
        },
    },
    userPreferences: {
        get: { url: '/user-preferences', verb: 'GET', retry: true },
        update: { url: '/user-preferences', verb: 'PATCH', retry: true },
    },
} as const;
