import {
    DEFAULT_APPLICATION_BOARD_SORT_ORDER,
    DEFAULT_APPLICATION_LIST_SORT_ORDER,
    JOB_STATUSES,
    type ArchivedJobApplication,
    type JobApplication,
} from '../../application/models';
import type { ArchivedJobInterview, JobInterview } from '../../interview/models';
import type { DemoState } from '../models';
import type { JobStatus } from '../../application/models';
import { daysAgo, daysFromNow, toDateString, weeksAgo } from './demoDateHelpers';
import { DEFAULT_INTERVIEW_DURATION_MINUTES, INTERVIEW_TIME_FILTERS } from '../../../helper/interviewTiming';

const defaultDemoPreferences = {
    application_job_statuses: [...JOB_STATUSES],
    application_show_notes: true,
    application_show_archive: true,
    application_enable_scroll: true,
    application_view_mode: 'list',
    application_list_sort_order: DEFAULT_APPLICATION_LIST_SORT_ORDER,
    application_board_sort_order: DEFAULT_APPLICATION_BOARD_SORT_ORDER,
    archived_application_job_statuses: [...JOB_STATUSES],
    archived_application_show_notes: true,
    archived_application_view_mode: 'list',
    archived_application_list_sort_order: DEFAULT_APPLICATION_LIST_SORT_ORDER,
    archived_application_board_sort_order: DEFAULT_APPLICATION_BOARD_SORT_ORDER,
    interview_view_mode: 'list',
    archived_interview_view_mode: 'list',
    interview_time_filters: [...INTERVIEW_TIME_FILTERS],
    archived_interview_time_filters: [...INTERVIEW_TIME_FILTERS],
} as const;

type ApplicationSeed = {
    companyName: string;
    daysAgo: number;
    id: number;
    jobLocation: string;
    jobStatus: JobStatus;
    jobTitle: string;
    notes: string;
};

type ArchivedApplicationSeed = Omit<ApplicationSeed, 'id'> & {
    id: number;
};

const createApplication = (seed: ApplicationSeed, now: Date): JobApplication => ({
    job_id: seed.id,
    company_name: seed.companyName,
    job_title: seed.jobTitle,
    application_date: toDateString(daysAgo(now, seed.daysAgo)),
    job_status: seed.jobStatus,
    job_location: seed.jobLocation,
    job_posting_url: '',
    notes: seed.notes,
});

const createArchivedApplication = (seed: ArchivedApplicationSeed, now: Date): ArchivedJobApplication => ({
    archived_job_id: seed.id,
    company_name: seed.companyName,
    job_title: seed.jobTitle,
    application_date: toDateString(daysAgo(now, seed.daysAgo)),
    job_status: seed.jobStatus,
    job_location: seed.jobLocation,
    job_posting_url: '',
    notes: seed.notes,
});

const applicationSeeds: ApplicationSeed[] = [
    {
        id: 101,
        companyName: 'HorizonAI Labs',
        jobTitle: 'Frontend Engineer',
        daysAgo: 5,
        jobStatus: 'Applied',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Role focuses on React dashboards and design-system cleanup.',
    },
    {
        id: 102,
        companyName: 'ByteForge Systems',
        jobTitle: 'Full Stack Developer',
        daysAgo: 11,
        jobStatus: 'Applied',
        jobLocation: 'Singapore - Remote',
        notes: '',
    },
    {
        id: 103,
        companyName: 'FinGrid Digital',
        jobTitle: 'Software Engineer, Payments',
        daysAgo: 18,
        jobStatus: 'Applied',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Follow up with recruiter after portfolio review.',
    },
    {
        id: 104,
        companyName: 'CloudNest Platform',
        jobTitle: 'React Platform Engineer',
        daysAgo: 25,
        jobStatus: 'Applied',
        jobLocation: 'Singapore',
        notes: '',
    },
    {
        id: 105,
        companyName: 'Orchid DataWorks',
        jobTitle: 'Backend Engineer',
        daysAgo: 36,
        jobStatus: 'Applied',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Interesting Node.js and PostgreSQL scope.',
    },
    {
        id: 106,
        companyName: 'Northstar Mobility',
        jobTitle: 'Product Engineer',
        daysAgo: 52,
        jobStatus: 'Applied',
        jobLocation: 'Kuala Lumpur - Remote from Singapore',
        notes: '',
    },
    {
        id: 107,
        companyName: 'Merlion Cloud',
        jobTitle: 'Senior Frontend Engineer',
        daysAgo: 7,
        jobStatus: 'Interview',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Prepare examples of accessibility and performance work.',
    },
    {
        id: 108,
        companyName: 'Atlas RecruitTech',
        jobTitle: 'Software Engineer, Platform',
        daysAgo: 16,
        jobStatus: 'Interview',
        jobLocation: 'Singapore - Remote',
        notes: '',
    },
    {
        id: 109,
        companyName: 'Harbour Analytics',
        jobTitle: 'Data Product Engineer',
        daysAgo: 27,
        jobStatus: 'Interview',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Bring examples of chart-heavy UI work.',
    },
    {
        id: 110,
        companyName: 'NovaStack',
        jobTitle: 'TypeScript Engineer',
        daysAgo: 41,
        jobStatus: 'Interview',
        jobLocation: 'Hong Kong - Remote',
        notes: '',
    },
    {
        id: 111,
        companyName: 'Greenhouse CloudOps',
        jobTitle: 'DevOps UI Engineer',
        daysAgo: 9,
        jobStatus: 'Offer',
        jobLocation: 'Singapore',
        notes: 'Review compensation and growth path.',
    },
    {
        id: 112,
        companyName: 'Quantum Ledger',
        jobTitle: 'Frontend Infrastructure Engineer',
        daysAgo: 30,
        jobStatus: 'Offer',
        jobLocation: 'Tokyo - Remote',
        notes: '',
    },
    {
        id: 113,
        companyName: 'Pinecone Health',
        jobTitle: 'Application Engineer',
        daysAgo: 44,
        jobStatus: 'Accepted',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Accepted verbal offer; paperwork expected next week.',
    },
    {
        id: 114,
        companyName: 'Aster Security',
        jobTitle: 'Security Tooling Engineer',
        daysAgo: 6,
        jobStatus: 'Rejected',
        jobLocation: 'Singapore',
        notes: 'Rejected after take-home assignment.',
    },
    {
        id: 115,
        companyName: 'TransitFlow',
        jobTitle: 'Web Engineer',
        daysAgo: 23,
        jobStatus: 'Rejected',
        jobLocation: 'Singapore - Hybrid',
        notes: '',
    },
    {
        id: 116,
        companyName: 'BluePeak Commerce',
        jobTitle: 'Checkout Platform Engineer',
        daysAgo: 49,
        jobStatus: 'Rejected',
        jobLocation: 'Singapore - Remote',
        notes: 'Strong feedback on frontend; role shifted to backend-heavy scope.',
    },
    {
        id: 117,
        companyName: 'Nimbus Freight',
        jobTitle: 'Logistics Software Engineer',
        daysAgo: 14,
        jobStatus: 'Ghosted',
        jobLocation: 'Singapore - Hybrid',
        notes: '',
    },
    {
        id: 118,
        companyName: 'Vector Learning',
        jobTitle: 'Education Platform Engineer',
        daysAgo: 38,
        jobStatus: 'Ghosted',
        jobLocation: 'Remote - APAC',
        notes: 'No response after initial recruiter call.',
    },
    {
        id: 119,
        companyName: 'Saffron Robotics',
        jobTitle: 'Robotics Dashboard Engineer',
        daysAgo: 20,
        jobStatus: 'Declined',
        jobLocation: 'Singapore - On-site',
        notes: 'Declined due to fully on-site requirement.',
    },
    {
        id: 120,
        companyName: 'Cedar FinTech',
        jobTitle: 'Senior React Engineer',
        daysAgo: 55,
        jobStatus: 'Declined',
        jobLocation: 'London - Remote',
        notes: '',
    },
];

const archivedApplicationSeeds: ArchivedApplicationSeed[] = [
    {
        id: 201,
        companyName: 'Riverlane Studio',
        jobTitle: 'Frontend Developer',
        daysAgo: 72,
        jobStatus: 'Rejected',
        jobLocation: 'Singapore',
        notes: 'Archived after rejection email.',
    },
    {
        id: 202,
        companyName: 'MapleStack',
        jobTitle: 'Full Stack Engineer',
        daysAgo: 81,
        jobStatus: 'Ghosted',
        jobLocation: 'Singapore - Remote',
        notes: '',
    },
    {
        id: 203,
        companyName: 'SilverRail Labs',
        jobTitle: 'UI Engineer',
        daysAgo: 88,
        jobStatus: 'Declined',
        jobLocation: 'Sydney - Remote',
        notes: 'Declined after compensation discussion.',
    },
    {
        id: 204,
        companyName: 'Keppel Digital',
        jobTitle: 'Software Engineer',
        daysAgo: 95,
        jobStatus: 'Offer',
        jobLocation: 'Singapore - Hybrid',
        notes: 'Archived older offer for comparison.',
    },
    {
        id: 205,
        companyName: 'OrbitPay',
        jobTitle: 'Frontend Engineer',
        daysAgo: 103,
        jobStatus: 'Accepted',
        jobLocation: 'Singapore',
        notes: '',
    },
];

const createInterviews = (now: Date): JobInterview[] => [
    {
        interview_id: 401,
        job_id: 107,
        company_name: 'Merlion Cloud',
        job_title: 'Senior Frontend Engineer',
        job_status: 'Interview',
        interview_date: toDateString(daysFromNow(now, 2, 10)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Google Meet',
        interview_type: 'HR screening call',
        interview_notes: 'Ask about frontend platform ownership.',
    },
    {
        interview_id: 402,
        job_id: 108,
        company_name: 'Atlas RecruitTech',
        job_title: 'Software Engineer, Platform',
        job_status: 'Interview',
        interview_date: toDateString(daysFromNow(now, 5, 14)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Zoom',
        interview_type: 'Technical interview',
        interview_notes: '',
    },
    {
        interview_id: 403,
        job_id: 109,
        company_name: 'Harbour Analytics',
        job_title: 'Data Product Engineer',
        job_status: 'Interview',
        interview_date: toDateString(daysFromNow(now, 9, 11)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'HarbourFront office',
        interview_type: 'Behavioural interview',
        interview_notes: 'Prepare dashboard tradeoff examples.',
    },
    {
        interview_id: 404,
        job_id: 110,
        company_name: 'NovaStack',
        job_title: 'TypeScript Engineer',
        job_status: 'Interview',
        interview_date: toDateString(daysFromNow(now, 14, 16)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Microsoft Teams',
        interview_type: 'Hiring-manager interview',
        interview_notes: '',
    },
    {
        interview_id: 405,
        job_id: 107,
        company_name: 'Merlion Cloud',
        job_title: 'Senior Frontend Engineer',
        job_status: 'Interview',
        interview_date: toDateString(daysAgo(now, 3, 15)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Phone call',
        interview_type: 'Recruiter follow-up',
        interview_notes: 'Completed; waiting for panel feedback.',
    },
    {
        interview_id: 406,
        job_id: 112,
        company_name: 'Quantum Ledger',
        job_title: 'Frontend Infrastructure Engineer',
        job_status: 'Offer',
        interview_date: toDateString(daysAgo(now, 8, 13)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Zoom',
        interview_type: 'Final discussion',
        interview_notes: 'Offer details shared after final round.',
    },
    {
        interview_id: 407,
        job_id: 108,
        company_name: 'Atlas RecruitTech',
        job_title: 'Software Engineer, Platform',
        job_status: 'Interview',
        interview_date: '2027-03-18T06:00:00.000Z',
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Zoom',
        interview_type: 'System design interview',
        interview_notes: 'Review platform scaling and API design examples.',
    },
    {
        interview_id: 408,
        job_id: 109,
        company_name: 'Harbour Analytics',
        job_title: 'Data Product Engineer',
        job_status: 'Interview',
        interview_date: '2027-11-04T03:00:00.000Z',
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'HarbourFront office',
        interview_type: 'Product case interview',
        interview_notes: '',
    },
    {
        interview_id: 409,
        job_id: 110,
        company_name: 'NovaStack',
        job_title: 'TypeScript Engineer',
        job_status: 'Interview',
        interview_date: '2028-06-22T08:00:00.000Z',
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Microsoft Teams',
        interview_type: 'Technical panel interview',
        interview_notes: 'Prepare TypeScript architecture tradeoffs.',
    },
];

const createArchivedInterviews = (now: Date): ArchivedJobInterview[] => [
    {
        archived_interview_id: 501,
        archived_job_id: 201,
        company_name: 'Riverlane Studio',
        job_title: 'Frontend Developer',
        job_status: 'Rejected',
        interview_date: toDateString(weeksAgo(now, 9, 11)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Zoom',
        interview_type: 'Technical interview',
        interview_notes: 'Archived with rejected application.',
    },
    {
        archived_interview_id: 502,
        archived_job_id: 203,
        company_name: 'SilverRail Labs',
        job_title: 'UI Engineer',
        job_status: 'Declined',
        interview_date: toDateString(weeksAgo(now, 11, 10)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Google Meet',
        interview_type: 'Portfolio review',
        interview_notes: '',
    },
    {
        archived_interview_id: 503,
        archived_job_id: 204,
        company_name: 'Keppel Digital',
        job_title: 'Software Engineer',
        job_status: 'Offer',
        interview_date: toDateString(weeksAgo(now, 12, 14)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Keppel Bay Tower',
        interview_type: 'Hiring-manager interview',
        interview_notes: 'Good team fit, offer received later.',
    },
    {
        archived_interview_id: 504,
        archived_job_id: 205,
        company_name: 'OrbitPay',
        job_title: 'Frontend Engineer',
        job_status: 'Accepted',
        interview_date: toDateString(weeksAgo(now, 13, 16)),
        interview_duration_minutes: DEFAULT_INTERVIEW_DURATION_MINUTES,
        interview_location: 'Microsoft Teams',
        interview_type: 'Behavioural interview',
        interview_notes: '',
    },
];

export const createDemoInitialState = (now = new Date()): DemoState => ({
    applications: applicationSeeds.map((seed) => createApplication(seed, now)),
    archivedApplications: archivedApplicationSeeds.map((seed) => createArchivedApplication(seed, now)),
    interviews: createInterviews(now),
    archivedInterviews: createArchivedInterviews(now),
    preferences: {
        ...defaultDemoPreferences,
        application_job_statuses: [...defaultDemoPreferences.application_job_statuses],
        archived_application_job_statuses: [...defaultDemoPreferences.archived_application_job_statuses],
        interview_time_filters: [...defaultDemoPreferences.interview_time_filters],
        archived_interview_time_filters: [...defaultDemoPreferences.archived_interview_time_filters],
    },
    nextApplicationId: 121,
    nextInterviewId: 410,
});
