name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build project
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Run tests
      run: npm test --if-present
      working-directory: ./frontend
  
  deploy:
    name: Deploy Frontend to Netlify
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Netlify via webhook
        run: curl "$NETLIFY_DEPLOY_WEBHOOK_URL"
        env:
          NETLIFY_DEPLOY_WEBHOOK_URL: ${{ secrets.NETLIFY_DEPLOY_WEBHOOK_URL }}
